### ISSUE TITLE
Spring Rest Template

### ISSUE THREAD

**Issue by ccit-spence** [mstahv/spring-data-vaadin-crud#1]
Looking at your example, would this be a way to add Spring RestTemplate like this example `https://spring.io/guides/gs/consuming-rest/` for consuming REST APIs.

The goal would be that Vaadin would be for UI and consuming REST from other services.

**Comment by mstahv** [comment]
Hi,

Pretty much yes. I'd hide the rest usage behind a service layer. So just instead of reading and saving from JpaRepository, you'd talk to class that behind the scenes makes REST calls.

cheers,
matti
