### ISSUE TITLE
dont know how to inject those components

### ISSUE THREAD

**Issue by gravin** [mstahv/spring-data-vaadin-crud#10]
as i know @SpringComponent  will use the default constructor, 
how does PersonForm to inject below 2 parameters? 
i didnt see any spring annotation for constructor

    PersonForm(PersonRepository r, EventBus.UIEventBus b) {

have same question on MainUI injection

**Comment by heutelbeck** [comment]
The recent versions of Spring do not require the @Autowired annotation on the constructor. It by default assumes, that the parameters need to be injected when that is the only available contructor.

**Comment by gravin** [comment]
thanks for reply, i also just found this
