### ISSUE TITLE
Spring Data Pagination and Lazy Loading

### ISSUE THREAD

**Issue by heutelbeck** [mstahv/spring-data-vaadin-crud#11]
Thanks for the example code here. My issue is probably related to: https://github.com/vaadin/vaadin-grid/issues/199

The calculation of the PageRequest breaks down for me. Given the code
```java
new PageRequest( offset / limit, limit)
```
For  collection with 101 entries, the grid issues two requests when scrolling through the collection:

* offset=0 limit=40  thus page=0
* offset=40 limit=61 thus page=0

And consequently my table ends up with only 61 entries.

There is a suggestion how to handle this to be found here: http://stackoverflow.com/questions/30217552/spring-data-pageable-and-limit-offset

The following implementation appears to solve the issue for the small example I am working with at the moement. Needs more testing though. But maybe you want to a address this issue in the example implementation here. I feel that this is something most people binding to spring data will run into this.

```java

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

/**
 * @see http://stackoverflow.com/questions/30217552/spring-data-pageable-and-limit-offset
 *
 */
public class OffsetSizePageRequest implements Pageable {

    private final int offset;
    private final int pageSize;
    private final Sort sort;

    public OffsetSizePageRequest(int offset, int pageSize) {
        this(offset, pageSize, null);
    }

    public OffsetSizePageRequest(int offset, int pageSize, Sort sort) {
        this.offset = offset;
        this.pageSize = pageSize;
        this.sort = sort;
    }

    @Override
    public int getPageNumber() {
        // this is the odd case, when the offset is > 0 but smaller than the page size.
        // That means that there actually is a previous page.
        if (getOffset() > 0 && getOffset() < getPageSize()) {
            return 1;
        }
        return getOffset() / getPageSize();
    }

    @Override
    public int getPageSize() {
        return pageSize;
    }

    @Override
    public int getOffset() {
        return offset;
    }

    @Override
    public Sort getSort() {
        return sort;
    }

    @Override
    public Pageable next() {
        return new OffsetSizePageRequest(getOffset() + getPageSize(), getPageSize(), getSort());
    }

    @Override
    public Pageable previousOrFirst() {
        if (getOffset() - getPageSize() <= 0) {
            return first();
        }
        return new OffsetSizePageRequest(getOffset() - getPageSize(), getPageSize(), getSort());
    }

    @Override
    public Pageable first() {
        if (getOffset() == 0) {
            return this;
        }
        return new OffsetSizePageRequest(0, getPageSize(), getSort());
    }

    @Override
    public boolean hasPrevious() {
        return getOffset() > 0;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + offset;
        result = prime * result + pageSize;
        result = prime * result + (sort == null ? 0 : sort.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        OffsetSizePageRequest other = (OffsetSizePageRequest) obj;
        if (offset != other.offset) {
            return false;
        }
        if (pageSize != other.pageSize) {
            return false;
        }
        if (sort == null) {
            if (other.sort != null) {
                return false;
            }
        } else if (!sort.equals(other.sort)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "OffsetSizePageRequest [offset=" + offset + ", pageSize=" + pageSize + ", sort=" + sort + "]";
    }

}

```

**Comment by mstahv** [comment]
The commented out lazy loading example is currently broken :-( I have been waiting for improvements to core, but I guess should just add the hacky solution that combines data from multiple pages...

This is probably the issue you want to follow:
https://github.com/vaadin/framework/issues/8982

**Comment by heutelbeck** [comment]
Thanks for the link. I agree this is currently a bit inefficient. But at least the custom page requests makes it work at all until the logic in core has been optimized.

**Comment by stevebor1** [comment]
+1 for some sort of Spring Pageable support

**Comment by dominic-simplan** [comment]
Hi, 
is this custom Pageable implementation still the best/recommended solution for making DataProvider work with Spring Data pageable repositories?
This solution (https://github.com/alejandro-du/lazy-loading-spring-demo/blob/master/src/main/java/com/example/PersonService.java) looks much simple, but I assume it's not working correctly then?

I am a bit confused because there are solutions/discussions about this topic on different sites and this custom Pageable implementation seems to come closest to an actual solution.

**Comment by mstahv** [comment]
The solution you linked kind of works, because of how Grid works, but it is really efficient and don't do what the dataprovider requests. The request by Vaadin may hit on two "pages"  -> you might need to merge parts of two pages (and that is not optimal either). 

I think this is what the add-on does as well, but really, there should not be a need for such at all. Please vote the issue in GitHub with thumb up so that it would be finally fixed in the future. Either vaadin/framework#8982 or https://github.com/vaadin/framework/issues/9289

**Comment by dominic-simplan** [comment]
@mstahv thanks for the fast reply and explanation. I've upvoted both issues 👍 .

I've tried the implementation from the lazy-loading-sprin-demo, but in some cases the grid showed empty lines after scrolling and keeps constantly triggering the backend for more data with the same offset and limit.
Now I've switched to the addon which seems to work great so far.

**Comment by mstahv** [comment]
Addon is fine. If you don't want that extra dependency, copy the solution by Johannes Häyry from vaadin/framework#8982

**Comment by mstahv** [comment]
The example now contains a working, but bit complex example, without add-on.

**Comment by idemin** [comment]
getPageNumber() should return 0, if offset< pageSize
