### ISSUE TITLE
multi-entities

### ISSUE THREAD

**Issue by dosindi** [mstahv/spring-data-vaadin-crud#15]
Tried to modify the master to support multi-entities for the below form but I get wrong number of type argument on ElementCollectionField. Do you have an implementation close to OneToMany relation for say User has Many roles?

![oneTomany](https://user-images.githubusercontent.com/1564400/55419883-675e8a00-557e-11e9-932a-fe895f7916ca.PNG)

![ManyToOne](https://user-images.githubusercontent.com/1564400/55420121-f79ccf00-557e-11e9-9ca6-9056ffdc75a7.png)

**Comment by mstahv** [comment]
Hi!

Any basic multiselect should do fine. Grid, ListBox, TwinColSelect, CheckBoxGroup...

**Comment by dosindi** [comment]
Well noted, Thank you.
