### ISSUE TITLE
Vaadin Directory repository is missing from pom.xml

### ISSUE THREAD

**Issue by martaolszewskatusiek** [mstahv/spring-data-vaadin-crud#16]
https://github.com/mstahv/spring-data-vaadin-crud/blob/4767161d4b49a410d474a58ee53d144711a1eaa5/pom.xml#L164

The link to Directory's repo is required because of flow-viritin.
The repository is: 
```
        <repository>
		   <id>vaadin-addons</id>
		   <url>https://maven.vaadin.com/vaadin-addons</url>
		</repository>
```

**Comment by mstahv** [comment]
Removed the dependency from the pit branch
