### ISSUE TITLE
Question about populating MTable

### ISSUE THREAD

**Issue by sachinkj** [mstahv/spring-data-vaadin-crud#3]
Hello! 

I am very new to Vaadin, and I have found your example very help in gaining a bit of familiarity with both Vaadin + Spring-data. I had a question about this chunk of code: 

list.setBeans(new SortableLazyList<>(
                // entity fetching strategy
                (firstRow, asc, sortProperty) -> repo.findAllBy(
                        new PageRequest(
                                firstRow / PAGESIZE, 
                                PAGESIZE,
                                asc ? Sort.Direction.ASC : Sort.Direction.DESC,
                                // fall back to id as "natural order"
                                sortProperty == null ? "id" : sortProperty
                        )
                ),
                () -> (int) repo.count(),
                PAGESIZE
        ));

If I understand correctly, this is what actually populates the MTable with data. I am trying to add another column to the MTable for instance a button that will link to another page, but I want that button for every row of data within the table. I am a bit confused about how you would go about adding such a column given this is how you populate the table to begin with. If you have any ideas that would be much appreciated. 

Thanks!
Sachin Jain

**Comment by mstahv** [comment]
Hi,

That indeed makes a "lazy loading data binding" from the database to the actual Vaadin Table component. The simpler java.util.List based binding is above.

If you want to add additional columns, which do not exist in your domain model, you should check out ColumnGenerator concept in Vaadin Table or its [improved Viritin version](https://github.com/viritin/viritin/blob/master/src/main/java/org/vaadin/viritin/fields/MTable.java#L339-L354) which has better typing. Just return a Link/Button in the given column generator. You can also use it to override the presentation of some properties.

cheers,
matti
