### ISSUE TITLE
error mvn install

### ISSUE THREAD

**Issue by rucko24** [mstahv/spring-data-vaadin-crud#8]
hi, 

I am presenting this error

`rubn@rubnPC:~/Documentos/java/aplicaciones/maven/spring-data-vaadin-crud-master$ mvn install
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-data-vaadin-crud 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:7.7.3:update-widgetset (default) @ spring-data-vaadin-crud ---
Error parsing jar file: file:/home/rubn/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
Error parsing jar file: file:/home/rubn/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
Error parsing jar file: file:/home/rubn/Documentos/java/aplicaciones/maven/spring-data-vaadin-crud-master/target/classes
Widgetsets found from classpath:
    org.vaadin.teemu.switchui.SwitchComponentWidgetset in file:/home/rubn/.m2/repository/org/vaadin/teemu/switch/2.0.2/switch-2.0.2.jar

Search took 14ms
[INFO] 1 addons found.
log4j:WARN No appenders could be found for logger (org.jboss.resteasy.plugins.providers.DocumentProvider).
log4j:WARN Please initialize the log4j system properly.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.588 s
[INFO] Finished at: 2016-10-24T11:43:41-04:30
[INFO] Final Memory: 24M/275M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:7.7.3:update-widgetset (default) on project spring-data-vaadin-crud: Execution default of goal com.vaadin:vaadin-maven-plugin:7.7.3:update-widgetset failed: A required class was missing while executing com.vaadin:vaadin-maven-plugin:7.7.3:update-widgetset: org/apache/commons/io/output/DeferredFileOutputStream
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.vaadin:vaadin-maven-plugin:7.7.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/rubn/.m2/repository/com/vaadin/vaadin-maven-plugin/7.7.3/vaadin-maven-plugin-7.7.3.jar
[ERROR] urls[1] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[2] = file:/home/rubn/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[3] = file:/home/rubn/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[4] = file:/home/rubn/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[5] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[6] = file:/home/rubn/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[7] = file:/home/rubn/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/home/rubn/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/home/rubn/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[10] = file:/home/rubn/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.1/maven-reporting-impl-2.1.jar
[ERROR] urls[11] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.jar
[ERROR] urls[12] = file:/home/rubn/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
[ERROR] urls[13] = file:/home/rubn/.m2/repository/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
[ERROR] urls[14] = file:/home/rubn/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[15] = file:/home/rubn/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
[ERROR] urls[16] = file:/home/rubn/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[17] = file:/home/rubn/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
[ERROR] urls[18] = file:/home/rubn/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
[ERROR] urls[19] = file:/home/rubn/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
[ERROR] urls[20] = file:/home/rubn/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[21] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar
[ERROR] urls[22] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar
[ERROR] urls[23] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.6/doxia-site-renderer-1.6.jar
[ERROR] urls[24] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.6/doxia-decoration-model-1.6.jar
[ERROR] urls[25] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar
[ERROR] urls[26] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar
[ERROR] urls[27] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[28] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
[ERROR] urls[29] = file:/home/rubn/.m2/repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
[ERROR] urls[30] = file:/home/rubn/.m2/repository/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar
[ERROR] urls[31] = file:/home/rubn/.m2/repository/commons-chain/commons-chain/1.1/commons-chain-1.1.jar
[ERROR] urls[32] = file:/home/rubn/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar
[ERROR] urls[33] = file:/home/rubn/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
[ERROR] urls[34] = file:/home/rubn/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar
[ERROR] urls[35] = file:/home/rubn/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar
[ERROR] urls[36] = file:/home/rubn/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar
[ERROR] urls[37] = file:/home/rubn/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[38] = file:/home/rubn/.m2/repository/org/springframework/spring-core/3.0.5.RELEASE/spring-core-3.0.5.RELEASE.jar
[ERROR] urls[39] = file:/home/rubn/.m2/repository/org/springframework/spring-asm/3.0.5.RELEASE/spring-asm-3.0.5.RELEASE.jar
[ERROR] urls[40] = file:/home/rubn/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[41] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.18/plexus-utils-3.0.18.jar
[ERROR] urls[42] = file:/home/rubn/.m2/repository/com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar
[ERROR] urls[43] = file:/home/rubn/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
[ERROR] urls[44] = file:/home/rubn/.m2/repository/com/vaadin/wscdn/wscdn-client/0.9.1/wscdn-client-0.9.1.jar
[ERROR] urls[45] = file:/home/rubn/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[ERROR] urls[46] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-client/3.0.10.Final/resteasy-client-3.0.10.Final.jar
[ERROR] urls[47] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-jaxrs/3.0.10.Final/resteasy-jaxrs-3.0.10.Final.jar
[ERROR] urls[48] = file:/home/rubn/.m2/repository/org/jboss/resteasy/jaxrs-api/3.0.10.Final/jaxrs-api-3.0.10.Final.jar
[ERROR] urls[49] = file:/home/rubn/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.1_spec/1.0.1.Final/jboss-annotations-api_1.1_spec-1.0.1.Final.jar
[ERROR] urls[50] = file:/home/rubn/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[51] = file:/home/rubn/.m2/repository/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar
[ERROR] urls[52] = file:/home/rubn/.m2/repository/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar
[ERROR] urls[53] = file:/home/rubn/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar
[ERROR] urls[54] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-jaxb-provider/3.0.10.Final/resteasy-jaxb-provider-3.0.10.Final.jar
[ERROR] urls[55] = file:/home/rubn/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.7/jaxb-impl-2.2.7.jar
[ERROR] urls[56] = file:/home/rubn/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.7/jaxb-core-2.2.7.jar
[ERROR] urls[57] = file:/home/rubn/.m2/repository/javax/xml/bind/jaxb-api/2.2.7/jaxb-api-2.2.7.jar
[ERROR] urls[58] = file:/home/rubn/.m2/repository/com/sun/istack/istack-commons-runtime/2.16/istack-commons-runtime-2.16.jar
[ERROR] urls[59] = file:/home/rubn/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.12/FastInfoset-1.2.12.jar
[ERROR] urls[60] = file:/home/rubn/.m2/repository/javax/xml/bind/jsr173_api/1.0/jsr173_api-1.0.jar
[ERROR] urls[61] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-jackson2-provider/3.0.10.Final/resteasy-jackson2-provider-3.0.10.Final.jar
[ERROR] urls[62] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.jar
[ERROR] urls[63] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.1/jackson-databind-2.4.1.jar
[ERROR] urls[64] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.4.1/jackson-annotations-2.4.1.jar
[ERROR] urls[65] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.4.1/jackson-jaxrs-json-provider-2.4.1.jar
[ERROR] urls[66] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.4.1/jackson-jaxrs-base-2.4.1.jar
[ERROR] urls[67] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.4.1/jackson-module-jaxb-annotations-2.4.1.jar
[ERROR] urls[68] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-archiver/2.6.3/plexus-archiver-2.6.3.jar
[ERROR] urls[69] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-io/2.1.3/plexus-io-2.1.3.jar
[ERROR] urls[70] = file:/home/rubn/.m2/repository/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[ERROR] urls[71] = file:/home/rubn/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[72] = file:/home/rubn/.m2/repository/junit/junit/4.11/junit-4.11.jar
[ERROR] urls[73] = file:/home/rubn/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[74] = file:/home/rubn/.m2/repository/org/apache/maven/surefire/surefire-booter/2.4.3/surefire-booter-2.4.3.jar
[ERROR] urls[75] = file:/home/rubn/.m2/repository/org/apache/maven/surefire/surefire-api/2.4.3/surefire-api-2.4.3.jar
[ERROR] urls[76] = file:/home/rubn/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[77] = file:/home/rubn/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[78] = file:/home/rubn/.m2/repository/org/jdom/jdom/1.1.3/jdom-1.1.3.jar
[ERROR] urls[79] = file:/home/rubn/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar
[ERROR] urls[80] = file:/home/rubn/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
[ERROR] urls[81] = file:/home/rubn/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar
[ERROR] urls[82] = file:/home/rubn/.m2/repository/xml-apis/xml-apis/1.3.02/xml-apis-1.3.02.jar
[ERROR] urls[83] = file:/home/rubn/.m2/repository/xom/xom/1.0/xom-1.0.jar
[ERROR] urls[84] = file:/home/rubn/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar
[ERROR] urls[85] = file:/home/rubn/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.jar
[ERROR] urls[86] = file:/home/rubn/.m2/repository/com/ibm/icu/icu4j/3.4.4/icu4j-3.4.4.jar
[ERROR] urls[87] = file:/home/rubn/.m2/repository/xerces/xercesImpl/2.10.0/xercesImpl-2.10.0.jar
[ERROR] urls[88] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.3/plexus-compiler-api-2.3.jar
[ERROR] urls[89] = file:/home/rubn/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[90] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-compiler-javac/2.3/plexus-compiler-javac-2.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.commons.io.output.DeferredFileOutputStream
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
rubn@rubnPC:~/Documentos/java/aplicaciones/maven/spring-data-vaadin-crud-master$ 
`

`rubn@rubnPC:~/Documentos/java/aplicaciones/maven/spring-data-vaadin-crud-master$ mvn spring-boot:run
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-data-vaadin-crud 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) > test-compile @ spring-data-vaadin-crud >>>
[INFO] 
[INFO] --- vaadin-maven-plugin:7.7.3:update-widgetset (default) @ spring-data-vaadin-crud ---
Error parsing jar file: file:/home/rubn/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
Error parsing jar file: file:/home/rubn/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
Error parsing jar file: file:/home/rubn/Documentos/java/aplicaciones/maven/spring-data-vaadin-crud-master/target/classes
Widgetsets found from classpath:
    org.vaadin.teemu.switchui.SwitchComponentWidgetset in file:/home/rubn/.m2/repository/org/vaadin/teemu/switch/2.0.2/switch-2.0.2.jar

Search took 14ms
[INFO] 1 addons found.
log4j:WARN No appenders could be found for logger (org.jboss.resteasy.plugins.providers.DocumentProvider).
log4j:WARN Please initialize the log4j system properly.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.532 s
[INFO] Finished at: 2016-10-24T12:05:38-04:30
[INFO] Final Memory: 24M/278M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:7.7.3:update-widgetset (default) on project spring-data-vaadin-crud: Execution default of goal com.vaadin:vaadin-maven-plugin:7.7.3:update-widgetset failed: A required class was missing while executing com.vaadin:vaadin-maven-plugin:7.7.3:update-widgetset: org/apache/commons/io/output/DeferredFileOutputStream
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.vaadin:vaadin-maven-plugin:7.7.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/rubn/.m2/repository/com/vaadin/vaadin-maven-plugin/7.7.3/vaadin-maven-plugin-7.7.3.jar
[ERROR] urls[1] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[2] = file:/home/rubn/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[3] = file:/home/rubn/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[4] = file:/home/rubn/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[5] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[6] = file:/home/rubn/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[7] = file:/home/rubn/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/home/rubn/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/home/rubn/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[10] = file:/home/rubn/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.1/maven-reporting-impl-2.1.jar
[ERROR] urls[11] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.jar
[ERROR] urls[12] = file:/home/rubn/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
[ERROR] urls[13] = file:/home/rubn/.m2/repository/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
[ERROR] urls[14] = file:/home/rubn/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[15] = file:/home/rubn/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
[ERROR] urls[16] = file:/home/rubn/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[17] = file:/home/rubn/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
[ERROR] urls[18] = file:/home/rubn/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
[ERROR] urls[19] = file:/home/rubn/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
[ERROR] urls[20] = file:/home/rubn/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[21] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar
[ERROR] urls[22] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar
[ERROR] urls[23] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.6/doxia-site-renderer-1.6.jar
[ERROR] urls[24] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.6/doxia-decoration-model-1.6.jar
[ERROR] urls[25] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar
[ERROR] urls[26] = file:/home/rubn/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar
[ERROR] urls[27] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[28] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
[ERROR] urls[29] = file:/home/rubn/.m2/repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
[ERROR] urls[30] = file:/home/rubn/.m2/repository/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar
[ERROR] urls[31] = file:/home/rubn/.m2/repository/commons-chain/commons-chain/1.1/commons-chain-1.1.jar
[ERROR] urls[32] = file:/home/rubn/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar
[ERROR] urls[33] = file:/home/rubn/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
[ERROR] urls[34] = file:/home/rubn/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar
[ERROR] urls[35] = file:/home/rubn/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar
[ERROR] urls[36] = file:/home/rubn/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar
[ERROR] urls[37] = file:/home/rubn/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[38] = file:/home/rubn/.m2/repository/org/springframework/spring-core/3.0.5.RELEASE/spring-core-3.0.5.RELEASE.jar
[ERROR] urls[39] = file:/home/rubn/.m2/repository/org/springframework/spring-asm/3.0.5.RELEASE/spring-asm-3.0.5.RELEASE.jar
[ERROR] urls[40] = file:/home/rubn/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[41] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.18/plexus-utils-3.0.18.jar
[ERROR] urls[42] = file:/home/rubn/.m2/repository/com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar
[ERROR] urls[43] = file:/home/rubn/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
[ERROR] urls[44] = file:/home/rubn/.m2/repository/com/vaadin/wscdn/wscdn-client/0.9.1/wscdn-client-0.9.1.jar
[ERROR] urls[45] = file:/home/rubn/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[ERROR] urls[46] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-client/3.0.10.Final/resteasy-client-3.0.10.Final.jar
[ERROR] urls[47] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-jaxrs/3.0.10.Final/resteasy-jaxrs-3.0.10.Final.jar
[ERROR] urls[48] = file:/home/rubn/.m2/repository/org/jboss/resteasy/jaxrs-api/3.0.10.Final/jaxrs-api-3.0.10.Final.jar
[ERROR] urls[49] = file:/home/rubn/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.1_spec/1.0.1.Final/jboss-annotations-api_1.1_spec-1.0.1.Final.jar
[ERROR] urls[50] = file:/home/rubn/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[51] = file:/home/rubn/.m2/repository/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar
[ERROR] urls[52] = file:/home/rubn/.m2/repository/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar
[ERROR] urls[53] = file:/home/rubn/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar
[ERROR] urls[54] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-jaxb-provider/3.0.10.Final/resteasy-jaxb-provider-3.0.10.Final.jar
[ERROR] urls[55] = file:/home/rubn/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.7/jaxb-impl-2.2.7.jar
[ERROR] urls[56] = file:/home/rubn/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.7/jaxb-core-2.2.7.jar
[ERROR] urls[57] = file:/home/rubn/.m2/repository/javax/xml/bind/jaxb-api/2.2.7/jaxb-api-2.2.7.jar
[ERROR] urls[58] = file:/home/rubn/.m2/repository/com/sun/istack/istack-commons-runtime/2.16/istack-commons-runtime-2.16.jar
[ERROR] urls[59] = file:/home/rubn/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.12/FastInfoset-1.2.12.jar
[ERROR] urls[60] = file:/home/rubn/.m2/repository/javax/xml/bind/jsr173_api/1.0/jsr173_api-1.0.jar
[ERROR] urls[61] = file:/home/rubn/.m2/repository/org/jboss/resteasy/resteasy-jackson2-provider/3.0.10.Final/resteasy-jackson2-provider-3.0.10.Final.jar
[ERROR] urls[62] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.jar
[ERROR] urls[63] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.1/jackson-databind-2.4.1.jar
[ERROR] urls[64] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.4.1/jackson-annotations-2.4.1.jar
[ERROR] urls[65] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.4.1/jackson-jaxrs-json-provider-2.4.1.jar
[ERROR] urls[66] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.4.1/jackson-jaxrs-base-2.4.1.jar
[ERROR] urls[67] = file:/home/rubn/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.4.1/jackson-module-jaxb-annotations-2.4.1.jar
[ERROR] urls[68] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-archiver/2.6.3/plexus-archiver-2.6.3.jar
[ERROR] urls[69] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-io/2.1.3/plexus-io-2.1.3.jar
[ERROR] urls[70] = file:/home/rubn/.m2/repository/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[ERROR] urls[71] = file:/home/rubn/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[72] = file:/home/rubn/.m2/repository/junit/junit/4.11/junit-4.11.jar
[ERROR] urls[73] = file:/home/rubn/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[74] = file:/home/rubn/.m2/repository/org/apache/maven/surefire/surefire-booter/2.4.3/surefire-booter-2.4.3.jar
[ERROR] urls[75] = file:/home/rubn/.m2/repository/org/apache/maven/surefire/surefire-api/2.4.3/surefire-api-2.4.3.jar
[ERROR] urls[76] = file:/home/rubn/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[77] = file:/home/rubn/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[78] = file:/home/rubn/.m2/repository/org/jdom/jdom/1.1.3/jdom-1.1.3.jar
[ERROR] urls[79] = file:/home/rubn/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar
[ERROR] urls[80] = file:/home/rubn/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
[ERROR] urls[81] = file:/home/rubn/.m2/repository/jdom/jdom/1.0/jdom-1.0.jar
[ERROR] urls[82] = file:/home/rubn/.m2/repository/xml-apis/xml-apis/1.3.02/xml-apis-1.3.02.jar
[ERROR] urls[83] = file:/home/rubn/.m2/repository/xom/xom/1.0/xom-1.0.jar
[ERROR] urls[84] = file:/home/rubn/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar
[ERROR] urls[85] = file:/home/rubn/.m2/repository/xalan/xalan/2.6.0/xalan-2.6.0.jar
[ERROR] urls[86] = file:/home/rubn/.m2/repository/com/ibm/icu/icu4j/3.4.4/icu4j-3.4.4.jar
[ERROR] urls[87] = file:/home/rubn/.m2/repository/xerces/xercesImpl/2.10.0/xercesImpl-2.10.0.jar
[ERROR] urls[88] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.3/plexus-compiler-api-2.3.jar
[ERROR] urls[89] = file:/home/rubn/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[90] = file:/home/rubn/.m2/repository/org/codehaus/plexus/plexus-compiler-javac/2.3/plexus-compiler-javac-2.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.commons.io.output.DeferredFileOutputStream
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
rubn@rubnPC:~/Documentos/java/aplicaciones/maven/spring-data-vaadin-crud-master$ 
`

**Comment by snicoll** [comment]
Can you please run `mvn dependency:purge-local-repository` on the project? Your local cache may have been corrupted. This will re-download all dependencies for this project. 

Thanks
